Notifications List component
antonpanchenk0/lms_system pull request #21
Opened 2021-08-30 14:32 UTC by knesko

For [#3 ](https://github.com/antonpanchenk0/lms_system/issues/3) 

1. Created notification component
2. Created notifications list component
3. Added redux (actions, reducer)
4. Created InitComponent

2021-08-30 16:15 UTC, kuprienko0 commented on frontend/src/global/styles/index.scss
>  htlm,
change to html, please

2021-08-30 19:43 UTC, yaroslavbilokin approved these changes

2021-08-30 20:03 UTC, antonpanchenk0 commented
`frontend/src/pages/InitComponent/InitComponent.scss` are we need this file?

`frontend/package-lock.json` please remove this one from changes. If this file not included to `.gitignore`, please will add it.

2021-08-30 20:09 UTC, antonpanchenk0 requested changes

2021-08-30 20:09 UTC, antonpanchenk0 commented on frontend/src/App.jsx
> +const App = () => <InitComponent />;
add this code here, please: 

```bash
import { BrowserRouter as Router, Switch } from 'react-router-dom'

const App = () => (
<Router>
  <Switch>
    <InitComponent />
  </Switch>
</Router>
)
```

2021-08-30 20:09 UTC, antonpanchenk0 commented on frontend/src/pages/InitComponent/components/NotificationList/Notification/Notification.jsx
> +    return null;
We need to clear interval when component will unmount

2021-08-30 20:09 UTC, antonpanchenk0 commented on frontend/src/pages/InitComponent/components/NotificationList/Notification/Notification.jsx
> +      return timeout;
I think this return is not necessary.

2021-08-31 13:34 UTC, antonpanchenk0 approved these changes

2021-08-31 13:35 UTC, yaroslavbilokin approved these changes

2021-08-31 15:30 UTC, merged